Files:

Net:
  name: 'Actor-Critic'
  use_bias: true
  bias_init_const: 0.0008
  grad_clip_norm: 10.0     # norm of gradients to clip
  n_filters: 64
  activation: 'elu'
  state_embedding_size: 128
  embedding_lr: 2.0e-4
  lr: 2.0e-4
  actor_coeff: 1.0
  critic_coeff: 1.0
  reg_coeff: 1.0e-4
  value_activation: 'identity'

Training:
  init_checkpoint: 0      # 0 for training from scratch, any > 0 number for restoring the model from the last checkpoint 
  n_iter: 100             # number of gradient descent steps at each iteration
  n_workers: 16
  display_every: 1
