Files:
  checkpoints_dir: 'checkpoints/'
  tensorboard_log_dir: 'tensorboard/'
  results_log_path: 'results.log'

Seed: 

Agent:
  name: 'actor-critic'
  gamma: 1.0
  Network:
    name: 'policy-value'
    use_bias: false
    bias_init_const: 0.0008
    grad_clip_norm: 10.0     # norm of gradients to clip
    n_filters: 64
    activation: 'elu'
    state_embedding_size: 128
    state_channels: 5
    lr: 1.0e-5
    actor_coeff: 1.0
    critic_coeff: 2.0
    reg_coeff: 1.0e-2
    entropy_coeff: 0.2
    value_activation: 'identity'

Training:
  init_checkpoint: 0      # 0 for training from scratch, any integer > 0 for restoring the model from the last checkpoint 
  n_iter: 200
  n_games: 16            
  n_workers: 8
  display_every: 5

Evaluation:
  n_games: 30
  n_workers: 10