Files:
  checkpoints_dir: 'checkpoints/'
  tensorboard_log_dir: 'tensorboard/'
  results_log_path: 'results.log'

Network:
  name: 'actor-critic'
  use_bias: true
  bias_init_const: 0.008
  grad_clip_norm: 5.0     # norm of gradients to clip
  n_filters: 64
  activation: 'elu'
  state_embedding_size: 128
  state_channels: 3
  lr: 1.0e-7
  actor_coeff: 0.15
  critic_coeff: 0.7
  reg_coeff: 1.0e-2
  value_activation: 'identity'

Training:
  init_checkpoint: 0      # 0 for training from scratch, any number > 0 for restoring the model from the last checkpoint 
  n_iter: 10
  n_games: 16            
  n_workers: 8
  display_every: 2

Evaluation:
  n_games: 30
  n_workers: 10