name:
  "FCPolicyValueNet"

architecture:
  embeddings:
    input_dim: 147 # 7*7*3
    hidden_dim: 256
    n_layers: 3
    bias: True

  policy_head:
    hidden_dim: 256
    output_dim: 132  #  N_ACTIONS = 33*4 = 132
    n_layers: 4 # 4
    bias: True

  value_head:
    hidden_dim: 256
    n_layers: 4
    bias: True

activation:
  name: "gelu"
  approximate: "tanh"

loss:
  actor_loss:
    name: "cross_entropy"
    reduction: "none"  # not mean because we need to multiply each sample in a batch by the advantage
    label_smoothing: 0.0001
    coef: 1.8
  critic_loss:
    name: "mse"
    reduction: "mean"
    coef: 1.0
  regularization:
    name: "entropy"
    coef: 0.000001


initializer:
  name: "he_normal"

optimizer:
  name: "adam"
  lr: 5.0e-5  # 2e-5
  weight_decay: 1.0e-6
